services:
  postgres:
    image: postgres:16
    container_name: petshop_db
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./исходные данные:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d petshop"]
      interval: 10s
      timeout: 5s
      retries: 10
